CREATE TABLE QUESTION(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    author VARCHAR(50),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPTIONS(
    idOption INTEGER PRIMARY KEY AUTO_INCREMENT,
    description VARCHAR(144) NOT NULL,
    votes INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE QUESTION ADD  optionOne INTEGER NOT NULL REFERENCES OPTIONS(idOption);

ALTER TABLE QUESTION ADD  optionTwo INTEGER NOT NULL REFERENCES OPTIONS(idOption);